POST /api/studies/abcd/files HTTP/1.1
Host: localhost:7071
Authorization: Basic m2c2:m2c2
Content-Length: 130
Content-Type: multipart/form-data; boundary=--abc123

----abc123
Content-Disposition: form-data; name="File"; filename="pic.jpg"
Content-Type: image/jpeg

< ./pic.jpg
----abc123--
