import { JsonSchema } from "./JsonSchema";

/**
 * ScoringSchema defines the data that are generated by the scoring code. They
 * are key-value pairs in which the key is the variable name, and the value is
 * JSON Schema that defines the type of the variable.
 */
export interface ScoringSchema {
  // The key is a single variable or datum produced by the scoring code. The JsonSchema is a simplified subset of JSON Schema
  [key: string]: JsonSchema;
}
