// UMD bundles can't be split. Therefore, this is the one bundle
// entry point with all exported classes, interfaces, and enums
// The UMD bundle will be used in unit testing and in the
// browser playground
export { WebColors } from "./WebColors";
export { Grid, GridOptions, Button, ButtonOptions } from "./addons/composites";
export { Instructions, InstructionsOptions } from "./addons/stories";
export {
  GameInitOptions,
  SvgImage,
  TapEvent,
  Point,
  Size,
  rgbaColor,
  tapListener,
  Game,
  ImageManager,
  FontManager,
  Transition,
  PushTransition,
  TransitionType,
  TransitionDirection,
  MoveActionOptions,
  WaitActionOptions,
  CustomActionOptions,
  ScaleActionOptions,
  Action,
  Constraints,
  Layout,
  Dimensions,
  EntityOptions,
  SceneOptions,
  DrawableOptions,
  TextOptions,
  TextLineOptions,
  LabelOptions,
  SpriteOptions,
  ShapeOptions,
  IDrawable,
  IText,
  EntityType,
  Entity,
  Scene,
  Sprite,
  LabelHorizontalAlignmentMode,
  Label,
  TextLine,
  Rect,
  RectOptions,
  Shape,
  Timer,
  RandomDraws,
  Composite,
  CompositeOptions,
  Story,
  StoryOptions,
} from "./m2c2kit";
