export class Constants {
  // This will be replaced by the package.json version at build time
  // Do not make this readonly.
  static M2C2KIT_SCHEMATICS_PACKAGE_VERSION =
    "__M2C2KIT_SCHEMATICS_PACKAGE_VERSION__";
  static M2C2KIT_CORE_PACKAGE_VERSION = "__M2C2KIT_CORE_PACKAGE_VERSION__";
  static M2C2KIT_ADDONS_PACKAGE_VERSION = "__M2C2KIT_ADDONS_PACKAGE_VERSION__";
  static M2C2KIT_SESSION_PACKAGE_VERSION =
    "__M2C2KIT_SESSION_PACKAGE_VERSION__";
  static M2C2KIT_BUILD_HELPERS_PACKAGE_VERSION =
    "__M2C2KIT_BUILD_HELPERS_PACKAGE_VERSION__";
  static M2C2KIT_SCHEMA_UTIL_PACKAGE_VERSION =
    "__M2C2KIT_SCHEMA_UTIL_PACKAGE_VERSION__";
  static CONCURRENTLY_VERSION = "__CONCURRENTLY_VERSION__";
  static RIMRAF_VERSION = "__RIMRAF_VERSION__";
  static ROLLUP_PLUGIN_LIVERELOAD_VERSION =
    "__ROLLUP_PLUGIN_LIVERELOAD_VERSION__";
  static ROLLUP_PLUGIN_SERVE_VERSION = "__ROLLUP_PLUGIN_SERVE_VERSION__";
  static TYPESCRIPT_VERSION = "__TYPESCRIPT_VERSION__";
  static ROLLDOWN_VERSION = "__ROLLDOWN_VERSION__";
  static CROSSENV_VERSION = "__CROSSENV_VERSION__";
}
