export class Constants {
  // This will be replaced by the package.json version at build time
  // Do not make this readonly.
  static M2C2KIT_SCHEMATICS_PACKAGE_VERSION =
    "__M2C2KIT_SCHEMATICS_PACKAGE_VERSION__";
  static M2C2KIT_CORE_PACKAGE_VERSION = "__M2C2KIT_CORE_PACKAGE_VERSION__";
  static M2C2KIT_ADDONS_PACKAGE_VERSION = "__M2C2KIT_ADDONS_PACKAGE_VERSION__";
  static M2C2KIT_SESSION_PACKAGE_VERSION =
    "__M2C2KIT_SESSION_PACKAGE_VERSION__";
  static M2C2KIT_BUILD_HELPERS_PACKAGE_VERSION =
    "__M2C2KIT_BUILD_HELPERS_PACKAGE_VERSION__";
}
