import { SessionKeyValueData } from "./SessionData";
import { SessionEvent } from "./SessionEvent";

/**
 * Data generated by the session.
 */
export interface SessionDataEvent extends SessionEvent {
  /** Data generated by the session. */
  data: SessionKeyValueData;
  /** Type of data. */
  dataType: "Diagnostics";
}
