# Build/test/publish packages to registries
name: CI/CD

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  # Allows running workflow manually from Actions tab
  workflow_dispatch:

# Allows reading repo contents, writing OIDC tokens, and writing code analysis events
permissions:
  contents: read
  id-token: write
  security-events: write

concurrency:
  group: "publish"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      # Fixes JS out of memory error; see https://github.com/actions/runner-images/issues/70
      NODE_OPTIONS: "--max_old_space_size=4096"
      # URL of the registry where public packages will be published. For npm, the URL is https://registry.npmjs.org
      PUBLIC_REGISTRY_URL: https://registry.npmjs.org
      # Use GitHub secrets to get token to authenticate with the organization npm-compatible registry. Token must have publish access.
      ORG_NPM_TOKEN: ${{ secrets.ORG_NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: npm
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: npm ci
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript-typescript
          queries: security-and-quality
          config: |
            paths-ignore:
              - '**/node_modules/**'
              - '**/dist/**'
              - '**/dist-webview/**'
              - '**/build/**'
              - '**/test/**'
              # these committed build artifacts are used in tests of hashing and should be ignored by CodeQL
              - 'packages/build-helpers/src/__tests__/dist-test/**'
              - '**/assets/**'
              - '**/coverage/**'
              - 'docs/**'
              - 'scripts/**'
              # schematics js build artifacts are placed alongside ts files; ignore them
              - 'packages/schematics/src/**/*.js'
              - 'examples/no-js-bundler-development/modules/**'
              - 'examples/android-simple-webview/**'
              - 'examples/ios-simple-webview/**'
      # See repo root Dockerfile for why this step is needed only when running in a container, like in GitHub Actions
      - name: Build and install @m2c2kit/schema-util
        run: npm run build -w @m2c2kit/schema-util && npm install -E -D @m2c2kit/schema-util
      - name: Build
        run: npm run build
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
      - name: Test
        run: npm run test
      - name: Integration test
        run: npm run integration-test
        timeout-minutes: 15
      - name: Publish updated packages
        # only packages explicitly named in scripts/publish-updated-packages.mjs will be published
        run: npm run publish-updated
        # publish-updated will set an environment variable PUBLIC_PACKAGES_OK to indicate if there were no errors with the public packages
      - name: Trigger static site deployment workflow
        if: ${{ env.PUBLIC_PACKAGES_OK=='true' }}
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.ORG_NPM_TOKEN }}" \
          https://api.github.com/repos/m2c2-project/static-site-approach/dispatches \
          -d '{"event_type":"package-published"}'
      - name: Trigger m2c2kit docs website deployment workflow
        if: ${{ env.PUBLIC_PACKAGES_OK=='true' }}
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.ORG_NPM_TOKEN }}" \
          https://api.github.com/repos/m2c2-project/m2c2kit-docs/dispatches \
          -d '{"event_type":"package-published"}'
